a=int(input())
if a==1: print('Январь Зима')
elif a==2: print('Февраль Зима')
elif a==3: print('Март весна')
elif a==4: print('Апрель весна')
elif a==5: print('Май весна')
elif a==6: print('Июнь лето')
elif a==7: print('Июль лето')
elif a==8: print('Август лето')
elif a==9: print('Сентябрь осень')
elif a==10: print('Октябрь осень')
elif a==11: print('Ноябрь осень')
elif a==12: print('Декабрь зима')
else: print('Ошибка')
